version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    # image: 279319081060/web:latest
    command: >
      sh -c "
      gunicorn conceptu.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./.envs/.production/.django.env
    restart: unless-stopped
    volumes:
      - .:/app

  db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    # image: 279319081060/db:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # - ./compose/production/postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file:
      - ./.envs/.production/.postgres.env
    ports:
      - '5432:5432'


  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    # image: 279319081060/nginx:latest
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 80:80
    depends_on:
      - web


volumes:
    static_volume:
    media_volume:
    postgres_data: