version: "3.3"
   
services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"