name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TEST_EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.TEST_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.TEST_REMOTE_USER }}
        TARGET: ${{ secrets.TEST_REMOTE_TARGET }}
    - name: Down the existing running Docker container
      run: |
        docker-compose -f production.yml down
    - name: Build the Docker image
      run: |
        docker-compose -f production.yml build
    - name: Run the Docker image
      run: |
        docker-compose -f production.yml up -d
    # - name: Run bash file
    #   run: |
    #     ls -la
    #     chmod +x hello.sh
    #     bash hello.sh 
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v3
    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Run bash script file
    #   run: |
    #     chmod +x ./hello.sh
    #   shell: bash
    # - name: Run Pre-Commit Tasks
    #   run: |
    #     pre-commit run --all-files
      
