name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deploy to Server 1
      uses: fifsky/ssh-action@master
      with:
        key: ${{ secrets.TEST_EC2_SSH_KEY }}
        host: ${{ secrets.TEST_REMOTE_HOST }}
        user : ${{ secrets.TEST_REMOTE_USER }}
        command: |
          ls -la
          cd test_code/ && bash hello.sh
    # - name: Run bash file
      # run: |
      #   ls -la
      #   chmod +x ./hello.sh
      #   ./hello.sh
      # shell: bash
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v3
    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Run bash script file
    #   run: |
    #     chmod +x ./hello.sh
    #   shell: bash
    # - name: Run Pre-Commit Tasks
    #   run: |
    #     pre-commit run --all-files
      
